### ISSUE TITLE
search ideas / todo

### ISSUE THREAD

**Issue by pierr** [get-focus/focus-search#4]
- [x] Tests of action builder and action creators
- [x] Reducer test
- [x] State shape as discussed maybe with `{criteria, results}` and all the corresponding data inside these nodes to separate them (also add a selector on each of them).
- [x] Middleware => need to be more generic (it should take the actions type on which its reacting), it should also be tested. ( maybe add the part of the state to add in the criteria)
- [x] Search components needs to be pure, take all the css and maybe the HTML structure of the existing components.
- PR => description + screenshots + tests :+1:

**Comment by Ephrame** [comment]
I have an interrogation about the middlewareBuilder, i want to open the criteria with a function. Doing this, shouldn't it be possible to add any object for the server request ?

**Comment by Ephrame** [comment]
@pierr For the state in the componant, for exemple isShowAllFacet, how we do that with the new search ?
