### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by Ephrame** [get-focus/focus-search#48]
- [x] add count AM
- [x] Add group actions (show more + show all) TO
- [x] style groups TO
- [x] lalalala to style TO
- [x] in scope all, add global actions AM
- [x] when a group is selected, display ungroup button directly AM
 ![image](https://cloud.githubusercontent.com/assets/10349407/19923964/274a3bb2-a0ea-11e6-8e17-a3164bc49a45.png)
